## Exercise 154

In [30]:
import pandas as pd
import numpy as np
df = pd.read_csv('HTRU_2.csv')
df.head()

140.5625  55.68378214  -0.234571412  -0.699648398  3.199832776  \
0  102.507812    58.882430      0.465318     -0.515088     1.677258   
1  103.015625    39.341649      0.323328      1.051164     3.121237   
2  136.750000    57.178449     -0.068415     -0.636238     3.642977   
3   88.726562    40.672225      0.600866      1.123492     1.178930   
4   93.570312    46.698114      0.531905      0.416721     1.636288   

   19.11042633  7.975531794  74.24222492  0  
0    14.860146    10.576487   127.393580  0  
1    21.744669     7.735822    63.171909  0  
2    20.959280     6.896499    53.593661  0  
3    11.468720    14.269573   252.567306  0  
4    14.545074    10.621748   131.394004  0

In [31]:
df = pd.read_csv('HTRU_2.csv', header=None)
df.columns = [['Mean of integrated profile', 'Standard deviation of integrated profile', 
               'Excess kurtosis of integrated profile', 'Skewness of integrated profile',
               'Mean of DM-SNR curve', 'Standard deviation of DM-SNR curve',
               'Excess kurtosis of DM-SNR curve', 'Skewness of DM-SNR curve', 'Class' ]]

df.head()

Mean of integrated profile Standard deviation of integrated profile  \
0                 140.562500                                55.683782   
1                 102.507812                                58.882430   
2                 103.015625                                39.341649   
3                 136.750000                                57.178449   
4                  88.726562                                40.672225   

  Excess kurtosis of integrated profile Skewness of integrated profile  \
0                             -0.234571                      -0.699648   
1                              0.465318                      -0.515088   
2                              0.323328                       1.051164   
3                             -0.068415                      -0.636238   
4                              0.600866                       1.123492   

  Mean of DM-SNR curve Standard deviation of DM-SNR curve  \
0             3.199833                          19.110426   
1             1.677258                          14.860146   
2             3.121237                          21.744669   
3             3.642977                          20.959280   
4             1.178930                          11.468720   

  Excess kurtosis of DM-SNR curve Skewness of DM-SNR curve Class  
0                        7.975532                74.242225     0  
1                       10.576487               127.393580     0  
2                        7.735822                63.171909     0  
3                        6.896499                53.593661     0  
4                       14.269573               252.567306     0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   (Mean of integrated profile,)                17898 non-null  float64
 1   (Standard deviation of integrated profile,)  17898 non-null  float64
 2   (Excess kurtosis of integrated profile,)     17898 non-null  float64
 3   (Skewness of integrated profile,)            17898 non-null  float64
 4   (Mean of DM-SNR curve,)                      17898 non-null  float64
 5   (Standard deviation of DM-SNR curve,)        17898 non-null  float64
 6   (Excess kurtosis of DM-SNR curve,)           17898 non-null  float64
 7   (Skewness of DM-SNR curve,)                  17898 non-null  float64
 8   (Class,)                                     17898 non-null  int64  
dtypes: float64(8), int64(1)
memory usage: 1.2 MB


## Exercise155

In [34]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [35]:
X = df.iloc[:, 0:8]
y = df.iloc[:, 8]

In [36]:
def clf_model(model):
    clf = model
    scores = cross_val_score(clf, X, y)
    print('Scores:', scores)
    print('Mean score:', scores.mean())

In [39]:
clf_model(LogisticRegression(max_iter=1000, random_state=0))

Scores: [0.97486034 0.97988827 0.98184358 0.97736798 0.9782062 ]
Mean score: 0.9784332723007113


## Exercise156

In [40]:
from sklearn.naive_bayes import GaussianNB
clf_model(GaussianNB())

Scores: [0.96061453 0.92374302 0.94273743 0.92847164 0.96451523]
Mean score: 0.9440163679814436


In [41]:
from sklearn.neighbors import KNeighborsClassifier
clf_model(KNeighborsClassifier())

Scores: [0.96955307 0.96927374 0.97318436 0.9706622  0.97289746]
Mean score: 0.9711141653437728


In [45]:
from sklearn.tree import DecisionTreeClassifier
clf_model(DecisionTreeClassifier(random_state=0))

Scores: [0.96843575 0.96424581 0.96871508 0.96227997 0.96954457]
Mean score: 0.9666442360073738


In [46]:
from sklearn.ensemble import RandomForestClassifier
clf_model(RandomForestClassifier(random_state=0))

Scores: [0.97709497 0.98324022 0.98072626 0.97485331 0.97848561]
Mean score: 0.978880074800083


## Exercise 157

In [16]:
df.Class.count()

Class    17898
dtype: int64

In [17]:
df[df.Class == 1].Class.count()

Class    1639
dtype: int64

In [18]:
df[df.Class == 1].Class.count()/df.Class.count()

Class    0.091574
dtype: float64

## Exercise 158

In [19]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [47]:
def confusion(model):
    clf = model
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    return clf

In [55]:
confusion(LogisticRegression(max_iter=1000))

[[4095   20]
 [  63  297]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4115
           1       0.94      0.82      0.88       360

    accuracy                           0.98      4475
   macro avg       0.96      0.91      0.93      4475
weighted avg       0.98      0.98      0.98      4475



LogisticRegression(max_iter=1000)

In [49]:
confusion(KNeighborsClassifier())

[[4077   38]
 [  69  291]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4115
           1       0.88      0.81      0.84       360

    accuracy                           0.98      4475
   macro avg       0.93      0.90      0.92      4475
weighted avg       0.98      0.98      0.98      4475



KNeighborsClassifier()

In [66]:
confusion(GaussianNB())

[[3946  169]
 [  52  308]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.97      4115
           1       0.65      0.86      0.74       360

    accuracy                           0.95      4475
   macro avg       0.82      0.91      0.85      4475
weighted avg       0.96      0.95      0.95      4475



GaussianNB()

In [68]:
confusion(RandomForestClassifier(random_state=0))

[[4096   19]
 [  57  303]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4115
           1       0.94      0.84      0.89       360

    accuracy                           0.98      4475
   macro avg       0.96      0.92      0.94      4475
weighted avg       0.98      0.98      0.98      4475



RandomForestClassifier()

## Exercise159

In [69]:
from sklearn.ensemble import AdaBoostClassifier
clf_model(AdaBoostClassifier())

Scores: [0.97430168 0.97988827 0.98128492 0.97597094 0.97708857]
Mean score: 0.977706874833175


In [70]:
confusion(AdaBoostClassifier())

[[4094   21]
 [  63  297]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4115
           1       0.93      0.82      0.88       360

    accuracy                           0.98      4475
   macro avg       0.96      0.91      0.93      4475
weighted avg       0.98      0.98      0.98      4475



AdaBoostClassifier()

In [27]:
import sys
!{sys.executable} -m pip install xgboost


[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: /Users/coreyjwade/opt/anaconda3/bin/python -m pip install --upgrade pip


In [71]:
from xgboost import XGBClassifier
clf_model(XGBClassifier())

Scores: [0.97765363 0.98156425 0.97932961 0.97680916 0.97876502]
Mean score: 0.9788243337532252


In [74]:
confusion(XGBClassifier())

[[4083   32]
 [  56  304]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4115
           1       0.90      0.84      0.87       360

    accuracy                           0.98      4475
   macro avg       0.95      0.92      0.93      4475
weighted avg       0.98      0.98      0.98      4475



XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)