In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('CHURN.csv')

In [3]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [5]:
df['Churn'] = df['Churn'].replace(to_replace=['No', 'Yes'], value=[0, 1])

In [6]:
X = df.iloc[:,1:-1] 
y = df.iloc[:, -1]

In [7]:
X = pd.get_dummies(X)

In [8]:
from sklearn.model_selection import cross_val_score

def clf_model (model, cv=3):
    clf = model
    scores = cross_val_score(clf, X, y, cv=cv)
    print('Scores:', scores)
    print('Mean score', scores.mean())

In [9]:
from sklearn.linear_model import LogisticRegression
clf_model(LogisticRegression(max_iter=1000))

Scores: [0.80238501 0.80238501 0.80400511]
Mean score 0.802925043315291


In [10]:
from sklearn.neighbors import KNeighborsClassifier
clf_model(KNeighborsClassifier())

Scores: [0.78109029 0.76192504 0.77290158]
Mean score 0.7719723028927428


In [11]:
from sklearn.naive_bayes import GaussianNB
clf_model(GaussianNB())

Scores: [0.27725724 0.28109029 0.27652322]
Mean score 0.2782902503153228


In [12]:
from sklearn.ensemble import RandomForestClassifier
clf_model(RandomForestClassifier())

Scores: [0.79045997 0.78407155 0.78994461]
Mean score 0.7881587087748638


In [13]:
from sklearn.ensemble import AdaBoostClassifier
clf_model(AdaBoostClassifier())

Scores: [0.80366269 0.80451448 0.80059651]
Mean score 0.8029245594131428


In [14]:
from xgboost import XGBClassifier
clf_model(XGBClassifier())

Scores: [0.7879046  0.77172061 0.78824031]
Mean score 0.782621839907265


In [15]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test ,y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [17]:
def confusion(model):
    clf = model
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    
    return clf

In [18]:
confusion(AdaBoostClassifier())

[[1145  137]
 [ 227  252]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1282
           1       0.65      0.53      0.58       479

    accuracy                           0.79      1761
   macro avg       0.74      0.71      0.72      1761
weighted avg       0.78      0.79      0.79      1761



AdaBoostClassifier()

In [22]:
confusion(RandomForestClassifier())

[[1164  118]
 [ 269  210]]
              precision    recall  f1-score   support

           0       0.81      0.91      0.86      1282
           1       0.64      0.44      0.52       479

    accuracy                           0.78      1761
   macro avg       0.73      0.67      0.69      1761
weighted avg       0.77      0.78      0.77      1761



RandomForestClassifier()

In [20]:
confusion(LogisticRegression(max_iter=1000))

[[1130  152]
 [ 202  277]]
              precision    recall  f1-score   support

           0       0.85      0.88      0.86      1282
           1       0.65      0.58      0.61       479

    accuracy                           0.80      1761
   macro avg       0.75      0.73      0.74      1761
weighted avg       0.79      0.80      0.80      1761



LogisticRegression(max_iter=1000)

In [24]:
confusion(AdaBoostClassifier(n_estimators=400))

[[1145  137]
 [ 228  251]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1282
           1       0.65      0.52      0.58       479

    accuracy                           0.79      1761
   macro avg       0.74      0.71      0.72      1761
weighted avg       0.78      0.79      0.79      1761



AdaBoostClassifier(n_estimators=400)

In [27]:
confusion(AdaBoostClassifier(n_estimators=35))

[[1143  139]
 [ 224  255]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86      1282
           1       0.65      0.53      0.58       479

    accuracy                           0.79      1761
   macro avg       0.74      0.71      0.72      1761
weighted avg       0.78      0.79      0.79      1761



AdaBoostClassifier(n_estimators=35)